version: '3'
services:
  tests:                     # Servicio para ejecutar pruebas
    build: .                 # Construye la imagen a partir del Dockerfile en el directorio actual
    volumes:
     - .:/app                # Monta el código fuente en el contenedor
    command: ["pytest"]      # Ejecuta el comando "pytest" al iniciar el contenedor

# Ejecucion de la API dentro del contenedor
  api:
    build: .                      # Construye la imagen a partir del Dockerfile en el directorio actual
    volumes:
     - .:/app                     # Monta el código fuente en el contenedor
    ports:
     - "5000:5000"                # Mapea el puerto 5000 del contenedor al puerto 5000 del host
    command: ["pytest", "app.py"] # Ejecuta el comando "python app.py" al iniciar el contenedor    

